# Generated by Django 4.2.7 on 2024-01-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0007_alter_project_description_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Project Manager', 'Project Manager'), ('Team Lead', 'Team Lead'), ('Developer', 'Developer'), ('Designer', 'Designer'), ('Quality Assurance Specialist', 'Quality Assurance Specialist')], max_length=50),
        ),
    ]
