# Generated by Django 4.2.7 on 2024-01-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0009_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, related_name='task_status', to='projectadmin.subtask'),
        ),
    ]
