# Generated by Django 4.2.7 on 2024-01-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0012_remove_project_complete_remove_task_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='status',
            new_name='current_status',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='description',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='title',
            new_name='name',
        ),
    ]
