# Generated by Django 4.2.7 on 2024-01-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0013_rename_status_subtask_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complete',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
